Update teaser
athene-aachen/athene-aachen pull request #11
Opened 2019-06-18 13:12 UTC by mgla

2019-06-28 13:58 UTC, Lilikon requested changes
Athene ist ein Bildungsprojekt. Unser Ziel ist es, die schulische Ausbildung von Kindern zu unterstützen und damit ihre Bildungschancen zu verbessern. Die Basis unserer Arbeit bildet schulische Nachhilfe an unseren Partnerschulen.
Wir sind ein kleiner studentisch geprägter Verein, der immer offen für neue Ideen und Dein Engagement ist.

2019-06-28 14:02 UTC, Lilikon commented on Mitmachen.md
>  Als Mentor_innen unterstützt du Lehrkräfte in Grund- und Sekundarschulen. Du begleitest den Unterricht und betreust bei Bedarf einzelne Kinder gezielt. Dafür musst du kein Mathe-Genie oder Sprachen-A
Als Mentor_in unterstützt du Lehrkräfte in Grund- und Sekundarschulen. Du begleitest vormittags den Unterricht und betreust bei Bedarf einzelne Kinder gezielt oder hilfst nachmittags bei der Hausaufgabenbetreuung. Dafür musst du kein Mathe-Genie oder Sprachen-Ass sein. Etwas Zeit und Motivation ist alles, was du brauchst.

2019-06-28 14:03 UTC, Lilikon commented on Mitmachen.md
> +### Arbeit am Wissensportal
Löschen

2019-06-28 14:03 UTC, Lilikon commented on Mitmachen.md
>  Unter der Kategorie [Wissen]({{ '/Wissen/' }}) bauen wir hier auf der Website eine Wissensplattform zum Thema Bildung ein, wo wir interessante, aber auch nützliche Informationen zum Thema Bildung auf
Löschen

2019-06-28 14:04 UTC, Lilikon commented on Mitmachen.md
>  Von Koordination mit den Schulen über Öffentlichkeitsarbeit bis hin zu Verwaltungsaufgaben im Verein - dein Einsatz ist gefragt!
Ergänzen: Außerdem bauen wir hier auf der Website unter der Kategorie [Wissen]({{ '/Wissen/' }}) eine Wissensplattform zum Thema Bildung ein, wo wir interessante, aber auch nützliche Informationen zum Thema Bildung aufbereiten und zusammenstellen. Auch hier freuen wir uns über deine Unterstützung.

2019-06-28 14:05 UTC, Lilikon commented on Mitmachen.md
> +### Zertifikat Internationales
Umbenennen: Zertifikate

2019-06-28 14:07 UTC, Lilikon commented on Mitmachen.md
> +Zum Dank stellen wir dir auf Wunsch ein [Zertifikat über deine Tätigkeit](https://www.rwth-aachen.de/cms/root/Studium/Im-Studium/Engagement-Freizeit/Engagement-International/~bqxh/Zertifikat-Internat
Außerdem kannst du dir dein Engagement auch als Teil des [Zertifikat Internationales](https://www.rwth-aachen.de/cms/root/Studium/Im-Studium/Engagement-Freizeit/Engagement-International/~bqxh/Zertifikat-Internationales/) der RWTH Aachen anrechnen lassen.

2019-06-29 20:44 UTC, mgla commented on Mitmachen.md
> +### Arbeit am Wissensportal
Die Ueberschrift komplett? Dann steht das bei Taaetigkeit als Mentor_in

2019-06-29 20:47 UTC, mgla commented on Mitmachen.md
> +### Arbeit am Wissensportal
ah, nvm

2019-06-29 20:48 UTC, mgla commented on Mitmachen.md
> +### Arbeit am Wissensportal
done

2019-06-29 20:48 UTC, mgla commented on Mitmachen.md
>  Von Koordination mit den Schulen über Öffentlichkeitsarbeit bis hin zu Verwaltungsaufgaben im Verein - dein Einsatz ist gefragt!
done

2019-06-29 20:50 UTC, mgla commented on Mitmachen.md
> +Zum Dank stellen wir dir auf Wunsch ein [Zertifikat über deine Tätigkeit](https://www.rwth-aachen.de/cms/root/Studium/Im-Studium/Engagement-Freizeit/Engagement-International/~bqxh/Zertifikat-Internat
Ist das nicht doppelt dann? Oder meinst du das stattdessen?

2019-06-29 21:00 UTC, mgla commented
uuuund live

2019-06-29 21:00 UTC, merged